name: maliput_full_build

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *' # 9:00am UTC, 1:00am PST.

env:
  PACKAGE_NAME: maliput_full
  ROS_DISTRO: foxy

jobs:
  compile_and_test:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.3
    - uses: ros-tooling/action-ros-ci@v0.2
      id: action_ros_ci_step
      with:
        package-name: ${{ env.PACKAGE_NAME }}
        target-ros2-distro: ${{ env.ROS_DISTRO }}
        vcs-repo-file-url: ${GITHUB_WORKSPACE}/maliput_full/repos/foxy/maliput_full.repos
